//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModusCreateNewsFeed.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArticleView
    {
        public System.Guid ArticleID { get; set; }
        public System.Guid FeedID { get; set; }
        public string Title { get; set; }
        public string Summary { get; set; }
        public Nullable<System.DateTime> DatePublished { get; set; }
        public string Author { get; set; }
        public string Link { get; set; }
        public string FeedName { get; set; }
        public string CategoryName { get; set; }
        public System.Guid CategoryID { get; set; }
    }
}
