//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModusCreateNewsFeed.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeedView
    {
        public System.Guid FeedID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Url { get; set; }
        public System.Guid CategoryID { get; set; }
        public string CategoryName { get; set; }
    }
}
